export type TaskTwoBlock = { id: string; label: string; title: string; english: string; chinese: string; fills: string[]; notes?: string[] };

export const taskTwoTypes = [
  { id: "agree", no: "01", title: "同意与否", titleEn: "Agree / Disagree", prompt: "To what extent do you agree or disagree?", template: "观点型母模板", focus: "明确立场" },
  { id: "discuss", no: "02", title: "双边讨论", titleEn: "Discuss Both Views", prompt: "Discuss both views and give your own opinion.", template: "观点型母模板", focus: "比较后判断" },
  { id: "outweigh", no: "03", title: "利弊权衡", titleEn: "Advantages / Disadvantages", prompt: "Do the advantages outweigh the disadvantages?", template: "观点型母模板", focus: "比较分量" },
  { id: "report", no: "04", title: "原因与对策", titleEn: "Causes & Solutions", prompt: "What are the causes and solutions?", template: "报告型母模板", focus: "问题—措施" },
];

export const opinionOpenings: TaskTwoBlock[] = [
  { id: "agree-opening", label: "开头 A · 同意与否", title: "明确反方、我方与两个理由", english: "In contemporary society, the question of whether 【完整句：题目争议】 has generated considerable debate. While some people maintain that 【完整句：反方观点】, I am convinced that 【完整句：我方立场】, primarily because of 【名词短语：理由1】 and 【名词短语：理由2】.", chinese: "在当代社会，【某件事是否应该发生】引发了广泛争议。尽管有人认为【反方】，但我相信【我方立场】，主要原因是【理由1】和【理由2】。", fills: ["反方怎么做", "你认为怎么做", "理由 1", "理由 2"] },
  { id: "discuss-opening", label: "开头 B · 双边讨论", title: "列出双方，再说明哪一方更有说服力", english: "In contemporary society, people hold differing views regarding 【名词短语：争议话题】. Some maintain that 【完整句：观点A】, whereas others believe that 【完整句：观点B】. Although both positions have merit, I find the 【former/latter】 view more persuasive, primarily because of 【名词短语：理由1】 and 【名词短语：理由2】.", chinese: "在当代社会，人们对于【争议话题】持有不同看法。一些人认为【观点 A】，另一些人则认为【观点 B】。尽管两种立场都有道理，我仍认为【前者／后者】更有说服力，主要原因是【理由 1】和【理由 2】。", fills: ["争议话题", "观点 A", "观点 B", "former / latter", "理由 1", "理由 2"], notes: ["支持前面观点 A，写 former；支持后面观点 B，写 latter。", "为了共用后面的主体段，先写不支持的一方，再写支持的一方。"] },
  { id: "outweigh-opening", label: "开头 C · 利弊权衡", title: "写清哪一方分量更大", english: "In contemporary society, the growing prevalence of 【名词或动名词：题目现象】 has generated considerable debate. Although this development brings both benefits and costs, I am convinced that its 【advantages/disadvantages】 outweigh its 【disadvantages/advantages】, primarily because of 【名词短语：理由1】 and 【名词短语：理由2】.", chinese: "在当代社会，【题目现象】日益普遍，引发了广泛争议。尽管这一发展同时带来益处和代价，我仍相信它的【优点／缺点】大于【缺点／优点】，主要原因是【理由 1】和【理由 2】。", fills: ["题目现象", "advantages / disadvantages", "理由 1", "理由 2"], notes: ["认为利大于弊，填 advantages outweigh disadvantages；反之则倒过来。", "第一段写较弱一方，第二段写更重要的一方。"] },
];

export const opinionBlocks: TaskTwoBlock[] = [
  { id: "concession", label: "主体段 1 · 让步段", title: "先承认较弱一方有合理性，再指出局限", english: "Admittedly, there is some justification for 【名词短语：反方观点、较弱一方或主要弊端】. The principal reason is that 【完整句：这一方成立的原因】, which means that 【完整句：它可能带来的直接结果】. A clear example can be seen in 【名词短语：具体场景】, where 【完整句：例子的具体情况】. This explains why this position may appear reasonable, particularly in the short term. Nevertheless, its overall value is limited because 【完整句：指出它的局限、代价或适用范围】.", chinese: "诚然，【较弱一方】具有一定合理性。主要原因是【原因】，这意味着【结果】。一个明显例子可以在【场景】中看到，在那里【例子细节】。这解释了为什么这一观点可能显得合理，尤其是在短期内。然而，它的整体价值仍然有限，因为【局限】。", fills: ["较弱一方", "成立原因", "直接结果", "具体场景与例子", "局限、代价或适用范围"], notes: ["it mainly produces short-term benefits and fails to address the underlying issue — 主要带来短期好处，无法解决根本问题。", "it is only effective under particular circumstances and cannot benefit everyone equally — 只在特定条件下有效，无法让所有人平等受益。", "the immediate benefits may be outweighed by the financial or social costs involved — 眼前收益可能被经济或社会代价抵消。"] },
  { id: "core", label: "主体段 2 · 核心论证", title: "重点论证我方为何更强", english: "Nevertheless, there are stronger reasons to support 【名词短语：我方观点、较强一方或主要优势】. To begin with, 【完整句：我方分论点1】. When 【完整句：相关条件或行为】, 【完整句：产生的直接结果】, thereby 【动名词短语：产生的进一步影响】. In addition, 【完整句：我方分论点2】. For instance, 【完整句：具体例子】. Taken together, these considerations suggest that 【完整句：说明我方为什么总体上更合理】.", chinese: "然而，有更充分的理由支持【我方】。首先，【分论点 1】。当【条件】时，【直接结果】，从而【进一步影响】。此外，【分论点 2】。例如，【具体例子】。综合来看，这些因素表明【为什么我方整体上更合理】。", fills: ["我方观点", "分论点 1", "条件／机制", "直接结果与进一步影响", "分论点 2", "具体例子"], notes: ["Taken together, these considerations suggest that this approach is more likely to produce lasting and widely shared benefits. — 这一做法更有可能产生持久且惠及更广泛群体的好处。", "只有题目确实涉及长远影响时，才使用 long-term challenges 等表达。"] },
  { id: "opinion-conclusion", label: "结尾段 · 统一收束", title: "重申立场，不引入新理由", english: "In conclusion, although 【名词短语或完整句：概括较弱一方】 should not be entirely overlooked, I remain convinced that 【完整句：重申明确立场】. This is because this position offers greater potential to 【动词原形：核心好处1】 and 【动词原形：核心好处2】, particularly from a long-term perspective.", chinese: "总之，尽管【较弱一方】不应该被完全忽视，但我仍然相信【我的立场】。这是因为这一立场更有可能【好处 1】并【好处 2】，尤其是从长远角度看。", fills: ["较弱一方", "明确立场", "核心好处 1", "核心好处 2"] },
];

export const reportBlocks: TaskTwoBlock[] = [
  { id: "report-opening", label: "开头段 · 报告型", title: "问题、两个原因、两类解决主体", english: "In contemporary society, 【名词短语：负面问题】 has become a matter of considerable concern. This issue is mainly caused by 【名词短语：原因1】 and 【名词短语：原因2】. Nevertheless, it can be effectively addressed through coordinated action by 【名词：主体1】 and 【名词：主体2】.", chinese: "在当代社会，【问题】已成为令人担忧的现象。它主要由【原因 1】和【原因 2】导致。不过，通过【主体 1】和【主体 2】采取协调行动，这一问题可以得到有效处理。", fills: ["负面问题", "原因 1", "原因 2", "主体 1", "主体 2"] },
  { id: "causes", label: "主体段 1 · 原因分析", title: "从原因到机制，再到后果", english: "Several interconnected factors account for this problem. The most important is 【名词短语：原因1】, because 【完整句：解释原因1如何导致问题】. When 【完整句：具体条件】, 【完整句：直接结果】, which in turn 【动词：进一步造成的后果】. Another contributing factor is 【名词短语：原因2】. A clear example can be seen in 【名词短语：具体场景】, where 【完整句：例子细节】. Taken together, these factors explain why 【完整句：题目问题持续或恶化】.", chinese: "几个相互关联的因素导致了这一问题。最重要的是【原因 1】，因为【解释】。当【条件】时，【直接结果】，进而【进一步后果】。另一个原因是【原因 2】。一个明显例子出现在【场景】中，在这里【例子细节】。综合来看，这些因素解释了为什么【问题持续或恶化】。", fills: ["原因 1 与机制", "具体条件", "直接结果与后果", "原因 2", "具体场景与例子", "问题如何恶化"], notes: ["个人层面：a lack of awareness、unhealthy habits、excessive dependence on technology。", "家庭／教育层面：insufficient parental guidance、limited access to appropriate education、excessive academic or workplace pressure。", "制度／社会层面：inadequate government regulation、unequal access to public resources、the pursuit of short-term economic gains。"] },
  { id: "solutions", label: "主体段 2 · 解决方案", title: "机构措施 + 个人／社区措施", english: "Nevertheless, a combination of targeted measures could substantially improve the situation. At the institutional level, 【政府、学校或企业】 should 【动词原形：措施1】. By doing so, they could 【动词原形：直接效果】, thereby 【动名词短语：进一步效果】. At the individual or community level, 【个人、家庭或社会组织】 should also be encouraged to 【动词原形：措施2】. For instance, 【完整句：措施如何实施】. If these measures were implemented together, they would not only 【动词原形：缓解当前问题】 but also 【动词原形：预防长期问题】.", chinese: "然而，一系列有针对性的措施可以显著改善情况。在制度层面，【政府、学校或企业】应该【措施 1】。通过这样做，它们能够【直接效果】，从而【进一步效果】。在个人或社区层面，还应鼓励【个人、家庭或组织】【措施 2】。例如，【具体实施方式】。如果这些措施共同实施，它们不仅能【缓解当前问题】，还能【预防长期问题】。", fills: ["制度主体与措施", "直接效果与进一步效果", "个人／社区主体与措施", "实施方式", "当前缓解与长期预防"], notes: ["机构措施：introduce stricter regulations；provide financial support；launch public education campaigns；improve access to public services。", "个人、家庭或学校：develop healthier habits；provide appropriate guidance；participate in community programmes；make informed decisions。"] },
  { id: "report-conclusion", label: "结尾段 · 报告型", title: "回扣原因与措施，强调可解决性", english: "In conclusion, although 【名词短语：问题】 is largely rooted in 【名词短语：原因1】 and 【名词短语：原因2】, it is by no means impossible to address. Through 【名词或动名词：措施1】 and 【名词或动名词：措施2】, its immediate effects can be reduced and its long-term recurrence can be prevented.", chinese: "总之，尽管【问题】主要源于【原因 1】和【原因 2】，但它并非无法解决。通过【措施 1】和【措施 2】，既可以减轻当前影响，也可以防止问题长期反复发生。", fills: ["问题", "原因 1 与原因 2", "措施 1 与措施 2"] },
];

export const taskTwoExamFlow = [
  { time: "05", title: "前 5 分钟：只写关键词", text: "观点型列出：立场、较弱一方原因、局限、我方两个理由和一个例子；报告型列出两个原因与两个对应措施。" },
  { time: "30", title: "接下来 30 分钟：按轨道展开", text: "先选对应开头，再依次写两个主体段和结尾。不要临时改变结构，也不要增加第三个主体段。" },
  { time: "05", title: "最后 5 分钟：只查四类错误", text: "检查单复数、第三人称单数、时态，以及每个句子是否有完整主语和谓语。" },
];
